# Generated by Django 4.0.6 on 2022-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyconfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='密钥名称', max_length=32, null=True, verbose_name='密钥名称')),
                ('platform', models.CharField(help_text='云平台', max_length=32, null=True, verbose_name='云平台')),
                ('appid', models.CharField(help_text='appid', max_length=32, null=True, verbose_name='appid')),
                ('appkey', models.CharField(help_text='appkey', max_length=64, null=True, verbose_name='appkey')),
            ],
            options={
                'verbose_name': '密钥名称',
                'db_table': 'key_configure',
                'ordering': ['id'],
            },
        ),
    ]
