# Generated by Django 4.0.6 on 2022-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyconfigure',
            name='name',
            field=models.CharField(help_text='密钥名称', max_length=32, null=True, unique=True, verbose_name='密钥名称'),
        ),
    ]
