# Generated by Django 4.0.6 on 2022-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_alter_keyconfigure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyconfigure',
            name='regionid',
            field=models.CharField(help_text='实例所属地域', max_length=32, null=True, verbose_name='实例所属地域'),
        ),
    ]
