# Generated by Django 4.0.6 on 2022-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceid', models.CharField(help_text='实例id', max_length=100, unique=True, verbose_name='实例id')),
                ('instancename', models.CharField(help_text='实例名称', max_length=32, null=True, verbose_name='实例名称')),
                ('instancetype', models.CharField(help_text='实例类型', max_length=255, verbose_name='实例类型')),
                ('hostname', models.CharField(help_text='主机名称', max_length=255, verbose_name='主机名称')),
                ('regionid', models.CharField(help_text='区域', max_length=255, verbose_name='区域')),
                ('zoneid', models.CharField(help_text='实例可用区', max_length=255, verbose_name='实例可用区')),
                ('osname', models.CharField(help_text='OS', max_length=255, verbose_name='OS')),
                ('ostype', models.CharField(help_text='os类型', max_length=255, verbose_name='os类型')),
                ('cpu', models.CharField(help_text='cpu', max_length=255, verbose_name='cpu')),
                ('memory', models.CharField(help_text='内存', max_length=255, verbose_name='内存')),
                ('public_ip', models.CharField(help_text='公网ip', max_length=255, verbose_name='公网ip')),
                ('primary_ip', models.CharField(help_text='内网ip', max_length=255, verbose_name='内网ip')),
                ('staus', models.CharField(help_text='运行状态', max_length=255, verbose_name='运行状态')),
                ('create_time', models.DateTimeField(help_text='创建时间', verbose_name='创建时间')),
                ('exprire_time', models.DateTimeField(help_text='过期时间', verbose_name='过期时间')),
                ('start_time', models.DateTimeField(help_text='启动时间', verbose_name='启动时间')),
            ],
            options={
                'db_table': 'instance_aliyun',
                'ordering': ['id'],
            },
        ),
    ]
