# Generated by Django 4.0.6 on 2022-08-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliyuninstance',
            name='create_time',
            field=models.DateTimeField(help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='aliyuninstance',
            name='exprire_time',
            field=models.DateTimeField(help_text='过期时间', null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='aliyuninstance',
            name='start_time',
            field=models.DateTimeField(help_text='启动时间', null=True, verbose_name='启动时间'),
        ),
    ]
