# Generated by Django 4.0.6 on 2022-08-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_alter_aliyuninstance_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliyuninstance',
            old_name='staus',
            new_name='status',
        ),
    ]
